server:
  port: 8080
spring:
  application:
    name: mind_map
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mind_map?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Yxd520..
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    # password:
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
mybatis-plus:
  configuration:
    # 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID